### ISSUE TITLE
Website doesn't have logo in tab

### ISSUE THREAD

**Issue by MarshalStewart** [Bearcat-Electric-Vehicle-BEV/BEV.github.io#21]
Add the BEV logo to the tab

**Comment by kevinosborn31** [comment]
Hi @MarshalStewart 

I can do this for you, do you mind please providing the file for the icon you would like to display on the tab?

Thanks in advance.

**Comment by MarshalStewart** [comment]
https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website

<link rel="icon" href="http://example.com/favicon.png">

**Comment by MarshalStewart** [comment]
Added logo in [eb7cd92](https://github.com/Bearcat-Electric-Vehicle-BEV/BEV.github.io/commit/eb7cd92d7a2f1c1ed9ac450b83ad1c7a8fd387fe)
